### ISSUE TITLE
Put test data into repository

### ISSUE THREAD

**Issue by bakhtos** [EvoTestOps/LogLead#28]
Currently the actual tests cannot be run because the data is only on authors' computer
Since there seems to be a special test batch, it can be checked into the repository.

**Comment by mmantyla** [comment]
The tests run through the following steps. They are linked via saved files with naming convention indicating which phase has created the data. First step takes in the huge raw data we have no permission to share. First step also samples it down and saves for steps 2 and 3. Step 0 is needed for downloading so that anyone can execute the full pipeline. Currently, step 0 has been done manually. 

1. https://github.com/EvoTestOps/LogLead/blob/c1c749829d04914d1ed5fd5d0415f927ea9cae2b/tests/loaders.py
2. https://github.com/EvoTestOps/LogLead/blob/c1c749829d04914d1ed5fd5d0415f927ea9cae2b/tests/enhancers.py
3. https://github.com/EvoTestOps/LogLead/blob/c1c749829d04914d1ed5fd5d0415f927ea9cae2b/tests/anomaly_detectors.py

**Comment by mmantyla** [comment]
The latest commit fixes this. Now data is downloaded when one trie to run main.py in tests folder. 
https://github.com/EvoTestOps/LogLead/commit/ddc85341cff53b9d53310c6467fe1d0ee44d59c3

Download data can also be run separatly. It does not overwrite. Rather it check if folder exists it does not download
https://github.com/EvoTestOps/LogLead/blob/main/tests/download_data.py

This config file controls what gets downloaded and tested. Commenting out rows disables downloading and testing 
https://github.com/EvoTestOps/LogLead/blob/main/tests/datasets.yml

**Comment by mmantyla** [comment]
@jnyyssol you had found couple of new datasets. Can you add them to config so they also get downloaded? Please also add them to tests.

**Comment by jnyyssol** [comment]
> @jnyyssol you had found couple of new datasets. Can you add them to config so they also get downloaded? Please also add them to tests.

This is a bit tricky, because the ADFA and AWSCTD datasets already consist of event IDs. Therefore most of the enhancements don't make sense, and some even cause it to crash. I got the tests to run with ADFA and AWSCTD by doing the following: 

1. Download the data (needs new `py7zr` package to unpack .7z)
2. Load the data and save these two directly with `_eh` which indicates they have been enhanced
3. This will cause the enhancer to skip them
4. Add a check in `anomaly_detectors.py` to ensure numeric columns exist (which they don't in these datasets, so many tests are skipped)

@mmantyla do you think it makes sense to include these two in the tests given that they are so different? Before pushing I still need to check that my changes didn't break anything regarding the other datasets.

**Comment by mmantyla** [comment]
I am closing this. Full test data will never be in LogLead repo. However, tests folders already has mechanism of downloading all supported datasets
